// [player, [missionNamespace, "inventory_var"]] call BIS_fnc_loadInventory;
// removeAllWeapons player;
// removeGoggles player;
// removeHeadgear player;
// removeVest player;
// removeUniform player;
// removeAllAssignedItems player;
// clearAllItemsFromBackpack player;
// removeBackpack player;
// player setUnitLoadout(player getVariable["Saved_Loadout",[]]);